services:

  db:
    container_name: tax_database_dev
    image: pgvector/pgvector:pg16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - "postgres-data-tax:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    env_file:
      - .env


volumes:
  postgres-data-tax:


