"""Update turn db model

Revision ID: 21b38fea83f4
Revises: d0bdc34c573e
Create Date: 2024-09-29 02:05:35.066824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '21b38fea83f4'
down_revision: Union[str, None] = 'd0bdc34c573e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_turns', sa.Column('user_action', sa.JSON(), nullable=False))
    op.alter_column('conversation_turns', 'requested_intent',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('conversation_turns', 'request')
    op.drop_column('conversation_turns', 'response')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_turns', sa.Column('response', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('conversation_turns', sa.Column('request', sa.TEXT(), autoincrement=False, nullable=False))
    op.alter_column('conversation_turns', 'requested_intent',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('conversation_turns', 'user_action')
    # ### end Alembic commands ###
