"""Update turn db model

Revision ID: d0bdc34c573e
Revises: b3ead1504241
Create Date: 2024-09-29 01:21:06.466422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd0bdc34c573e'
down_revision: Union[str, None] = 'b3ead1504241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_turns', sa.Column('session_id', sa.String(), nullable=False))
    op.add_column('conversation_turns', sa.Column('turn_id', sa.String(), nullable=False))
    op.drop_column('conversation_turns', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_turns', sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('conversation_turns', 'turn_id')
    op.drop_column('conversation_turns', 'session_id')
    # ### end Alembic commands ###
