"""Update turn db model

Revision ID: f782fe74e1ae
Revises: 2185f8820227
Create Date: 2024-09-29 05:43:55.079218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f782fe74e1ae'
down_revision: Union[str, None] = '2185f8820227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_turns', sa.Column('pcc_3_form', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_turns', 'pcc_3_form')
    # ### end Alembic commands ###
